Added in badge and refactored readme with automatic thumbnail generation (#11)
* Refactored readme with initial framing for automatic image convert

* Added in debugging

* Made conversion paths absolute

* Added in gs

* Cleaned out debugging statements

* Made thumbnail link to final output image

* Typo fix

* typo fix

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -35,10 +35,20 @@ function stash_push () {
     fi
 }
 
+# Generates the resume PDF
 info "Build: Generating resume document now"
 if xelatex Resume_Jason_Yao.tex ; then
     success "Build: Generated the new resume document"
 else
 		warn "Build: Failed to generate the new resume document"
 		exit 1
+fi
+
+# Generates the image thumbnail
+info "Thumbnail Build: Generating image thumbnail now"
+if convert -density 300 -quality 90 ${TRAVIS_BUILD_DIR}/Resume_Jason_Yao.pdf ${TRAVIS_BUILD_DIR}/Resume_Jason_Yao.png ; then
+    success "Thumbnail Build: Generated the new image thumbnail"
+else
+    warn "Thumbnail Build: Failed to generate the new image thumbnail"
+    exit 1
 fi
