Added in multiple file generations

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+tex_file_name=Resume_Jason_Yao.tex
+
 ###
 # Helper functions
 ##
@@ -35,14 +37,21 @@ function stash_push () {
     fi
 }
 
+function generate_resume () {
+    info "Build: Generating resume document now"
+			if xelatex $1 ; then
+			success "Build: Generated the new resume document"
+    else
+				warn "Build: Failed to generate the new resume document"
+				exit 1
+    fi
+}
+
 # Generates the resume PDF
-info "Build: Generating resume document now"
-if xelatex Resume_Jason_Yao.tex ; then
-    success "Build: Generated the new resume document"
-else
-		warn "Build: Failed to generate the new resume document"
-		exit 1
-fi
+for resume_generation in {1..3}
+do
+		generate_resume ${tex_file_name}
+done
 
 # Generates the image thumbnail
 info "Thumbnail Build: Generating image thumbnail now"
