Attempt 1 for setting up texlive properly

diff --git a/bin/install_dependencies b/bin/install_dependencies
--- a/bin/install_dependencies
+++ b/bin/install_dependencies
@@ -91,18 +91,53 @@ function install_latex_package() {
 		success "Latex Package Install: Successfully installed ${package_name}"
 }
 
-mkdir -p ~/texmf
+# TODO P0: Remove after
+# mkdir -p ~/texmf
+#
+# for latex_dependency_package in "${!latex_dependency_packages[@]}"
+# do
+# 	install_latex_package $latex_dependency_package ${latex_dependency_packages[$latex_dependency_package]}
+# done
+#
+# success "Latex Package Install: Successfully compiled all dependencies"
+#
+# if texhash ~/texmf ; then
+#     success "Latex Package Install: Successfully installed all packages into TDS"
+# else
+#     warning "Latex Package Install: Failed to install all packages into TDS"
+# 		exit 1
+# fi
 
-for latex_dependency_package in "${!latex_dependency_packages[@]}"
-do
-	install_latex_package $latex_dependency_package ${latex_dependency_packages[$latex_dependency_package]}
-done
 
-success "Latex Package Install: Successfully compiled all dependencies"
 
-if texhash ~/texmf ; then
-    success "Latex Package Install: Successfully installed all packages into TDS"
-else
-    warning "Latex Package Install: Failed to install all packages into TDS"
-		exit 1
+
+# See if there is a cached version of TL available
+export PATH=/tmp/texlive/bin/x86_64-linux:$PATH
+if ! command -v texlua > /dev/null; then
+  # Obtain TeX Live
+  wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz
+  tar -xzf install-tl-unx.tar.gz
+  cd install-tl-20*
+
+  # Install a minimal system
+  ./install-tl --profile=../bin/texlive.profile
+
+  cd ..
 fi
+
+# Just including texlua so the cache check above works
+# Needed for any use of texlua even if not testing LuaTeX
+tlmgr install luatex
+
+# Other contrib packages: done as a block to avoid multiple calls to tlmgr
+# texlive-latex-base is needed to run pdflatex
+tlmgr install   \
+  datetime2          \
+  tracklang
+	# TODO P0: Add in fontawesome
+
+# Keep no backups (not required, simply makes cache bigger)
+tlmgr option -- autobackup 0
+
+# Update the TL install but add nothing new
+tlmgr update --self --all --no-auto-install
